# Generated by Django 4.2.10 on 2024-02-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trashpetapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="petals",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
