# Generated by Django 5.0.2 on 2024-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavesCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('leaves', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bought',
            field=models.CharField(default='{"Cap": false, "Crown": false, "Socks": false, "Bottle": false}', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accessories',
            field=models.CharField(default='{"Cap": false, "Crown": false, "Socks": false, "Bottle": true}', max_length=200),
        ),
    ]
