# Generated by Django 4.2.10 on 2024-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trashpetapp", "0002_member_petals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="petals",
            field=models.IntegerField(default=0),
        ),
    ]
