# Generated by Django 4.2.10 on 2024-02-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trashpetapp", "0004_userprofile_delete_member"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="petals",
            new_name="leaves",
        ),
    ]
