# Generated by Django 4.2.10 on 2024-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trashpetapp", "0005_rename_petals_userprofile_leaves"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pet_name",
            field=models.CharField(default="Trash Pet", max_length=30),
        ),
    ]
