# Generated by Django 4.2.10 on 2024-02-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trashpetapp", "0006_userprofile_pet_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=20)),
                ("locked", models.BooleanField()),
                ("code", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("link", models.CharField(max_length=100)),
            ],
        ),
    ]
