# Generated by Django 4.2.9 on 2024-02-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0006_userprofile_pet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codes',
            field=models.CharField(default='', max_length=30),
        ),
    ]
