# Generated by Django 4.2.10 on 2024-02-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trashpetapp", "0007_accessory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="codes",
            field=models.CharField(default="", max_length=30),
        ),
    ]
