# Generated by Django 4.2.9 on 2024-02-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0007_accessory'),
        ('trashpetapp', '0007_userprofile_codes'),
    ]

    operations = [
    ]
