# Generated by Django 4.2.9 on 2024-03-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0007_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accessories',
            field=models.CharField(default='{"Cap": false, "Crown": false, "Socks": false, "Bottle": true}', max_length=200),
        ),
    ]
