# Generated by Django 4.2.10 on 2024-03-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trashpetapp", "0008_merge_0007_accessory_0007_userprofile_codes"),
    ]

    operations = [
        
        migrations.AddField(
            model_name="userprofile",
            name="accessories",
            field=models.CharField(
                default='{"Cap": false, "Crown": false, "Socks": false, "Bottle": true}',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bought",
            field=models.CharField(
                default='{"Cap": false, "Crown": false, "Socks": false, "Bottle": false}',
                max_length=200,
            ),
        ),
    ]
