# Generated by Django 4.2.9 on 2024-02-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0008_merge_0007_accessory_0007_userprofile_codes'),
        ('trashpetapp', '0008_userprofile_codes'),
    ]

    operations = [
    ]
