# Generated by Django 4.2.10 on 2024-03-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trashpetapp", "0008_userprofile_accessories"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bought",
            field=models.CharField(
                default='{"Cap": false, "Crown": false, "Socks": false, "Bottle": false}',
                max_length=200,
            ),
        ),
    ]
