# Generated by Django 5.0.2 on 2024-02-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0009_merge_20240228_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='codes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accessories',
            field=models.CharField(default='{"Cap": true, "Crown": false, "Socks": false, "Bottle": true}', max_length=200),
        ),
    ]
