# Generated by Django 4.2.9 on 2024-03-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0009_leavescode_userprofile_used_codes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavescode',
            old_name='code',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='used_codes',
        ),
        
        
 
    ]
