# Generated by Django 5.0.2 on 2024-03-18 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0002_leavescode_userprofile_bought_and_more'),
        ('trashpetapp', '0011_add_bought'),
    ]

    operations = [
    ]
