# Generated by Django 4.2.9 on 2024-03-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0012_marker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='link',
        ),
        migrations.AddField(
            model_name='accessory',
            name='image',
            field=models.ImageField(default='cap.png', upload_to='images/'),
        ),
    ]
