# Generated by Django 4.2.9 on 2024-03-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0013_remove_accessory_link_accessory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='link',
            field=models.CharField(default='/images/cap.png', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(default='images/cap.png', upload_to='images/'),
        ),
    ]
