# Generated by Django 4.2.9 on 2024-03-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0015_userprofile_locked_list_alter_accessory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pet_colour',
            field=models.CharField(default='petbackground.png', max_length=30),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(default='cap.png', upload_to='static/images/'),
        ),
    ]
