# Generated by Django 5.0.3 on 2024-03-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "trashpetapp",
            "0015_alter_accessory_image_alter_userprofile_accessories_and_more",
        ),
        ("trashpetapp", "0016_userprofile_pet_colour_alter_accessory_image"),
    ]

    operations = []
