# Generated by Django 4.2.9 on 2024-03-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0016_userprofile_pet_colour_alter_accessory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accessories',
            field=models.CharField(default='"{\\"socks\\": False, \\"bottle\\": False, \\"crown\\":False, \\"cap\\": False}"', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bought',
            field=models.CharField(default='"{\\"socks\\": False, \\"bottle\\": True, \\"crown\\":False, \\"cap\\": False}"', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='locked_list',
            field=models.CharField(default='"{\\"socks\\": False, \\"bottle\\": True, \\"crown\\":False, \\"cap\\": False}"', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pet_colour',
            field=models.CharField(default='/static/images/petbackground.png', max_length=50),
        ),
    ]
