# Generated by Django 4.2.9 on 2024-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0017_alter_userprofile_accessories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accessories',
            field=models.CharField(default='{"socks": false, "bottle": false, "crown": false, "cap": false}', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bought',
            field=models.CharField(default='{"socks": false, "bottle": true, "crown": false, "cap": false}', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='locked_list',
            field=models.CharField(default='{"socks": false, "bottle": true, "crown": false, "cap": false}', max_length=200),
        ),
    ]
