# Generated by Django 5.0.3 on 2024-03-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trashpetapp", "0017_merge_20240320_1219"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessory",
            name="image",
            field=models.ImageField(default="cap.png", upload_to="static/images/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pet_colour",
            field=models.CharField(
                default="/static/images/petbackground.png", max_length=50
            ),
        ),
    ]
