# Generated by Django 4.2.9 on 2024-03-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashpetapp', '0018_remove_accessory_image_alter_userprofile_accessories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bought',
            new_name='bought_list',
        ),
    ]
